services:

  mongo:
    image: mongo:4
    restart: unless-stopped

  caronte:
    image: ghcr.io/pwnzer0tt1/caronte:latest
    ports:
      - "3333:3333"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
    depends_on:
      - mongo
    restart: unless-stopped

